# Generated by Django 3.1.7 on 2021-08-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210815_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='postCode',
        ),
    ]
